### ISSUE TITLE
Login with empty text of password.

### ISSUE THREAD

**Issue by smilesm2** [billchurch/WebSSH2#118]
hi, 
Thanks for this project. It really help me a lot.
But I found out that if I login with an empty text password, it will not be able to login and type account and password again until restart my browser(Chrome).
I think that is because Chrome remember basic-auth with my empty password.
So I add a if addition `myAuth.pass !== ""` on `WebSSH2/app/server/util.js:12`
```
var myAuth = Auth(req)
if (myAuth && myAuth.pass !== "") {
    req.session.username = myAuth.name
```
And now the input box of login will appear again just like inputing a wrong password!

**Comment by billchurch** [comment]
Okay, I see your problem here... I think I need to solve it a different way, because it's entirely possible that one could have a blank password... `PermitEmptyPasswords` is a setting in OpenSSH. Let me take a look at this.

And, it should re-prompt if you after a failure, if you have the `allowreauth` option set to true, which it currently does not. The problem is in my logic. Standby.

**Comment by billchurch** [comment]
Okay, I need to spend more time on that to support a blank password, for now your suggestion will work fine.
