### ISSUE TITLE
Additional ports tunneling?

### ISSUE THREAD

**Issue by rnditdev** [billchurch/WebSSH2#121]
Hello,

In order to allow securely connecting with web services running on the destination machines, it would be useful to be able to transport additional ports via the current URL, adding the destination port. 

For example, based on the homepage example page, to connect to a tunneled socket originally on port 8080 of the destination machine (localhost), we would use the URL http://localhost:2222/ssh/host/127.0.0.1:8080.

Best Regards.

**Comment by billchurch** [comment]
Provided that the port is already tunneled on that machine, You can specifying a different SSH port to connect to using the `?port=8080` GET var on the URL. This _is_ documented on the main README.md file.

Your example:
```
http://localhost:2222/ssh/host/127.0.0.1?port=8080
```

If, otherwise, you want to create an actual tunnel from the browser over the WebSSH2 client to another server, that's not possible due to browser sandboxing without some sort of client-side component, which is out of scope for this project.
