### ISSUE TITLE
BUG: Uncaught ReferenceError: logBtn is not defined

### ISSUE THREAD

**Issue by thiago-paz** [billchurch/webssh2#141]
What is happening is that after log in into servers with same username and password, I can no longer login to the servers w/ other user/pass because the authentication popup is not being shown anymore.

In the google chrome console, I got this error:

Uncaught ReferenceError: logBtn is not defined  -  webssh2.bundle.js:1 

config.json:
  "options": {
    "challengeButton": true,
    "allowreauth": true
  }

WebSSH2 Version 0.2.9

```
~# node -v
v10.16.0
~# npm -v
6.9.0
~# lsb_release -a
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial
```

**Comment by billchurch** [comment]
i can't replicate this, do you have any logs or maybe a video showing it?

**Comment by AronMarinelli** [comment]
I just ran into this issue as well. It seems to occur whenever incorrect login details are entered in the basic auth popup.

This error is printed on screen:
<img width="428" alt="Screenshot_1" src="https://user-images.githubusercontent.com/5307205/76144106-413e4580-607d-11ea-9777-cda776ae675f.png">

And the following appears in my console:
<img width="375" alt="Screenshot_2" src="https://user-images.githubusercontent.com/5307205/76144108-44393600-607d-11ea-9503-d31805c0dd52.png">

The error is being caused by the drawMenu() function which is called when the socket emits allowreauth. Probably something to do with only the reauth button being present, making functions called on the other buttons cause a null reference error.

drawMenu reference:
https://github.com/billchurch/webssh2/blob/42f973b4796f7f50237dc8ce613e477aa89352ca/app/client/src/js/index.js#L132
drawMenu function:
https://github.com/billchurch/webssh2/blob/42f973b4796f7f50237dc8ce613e477aa89352ca/app/client/src/js/index.js#L165

**Comment by billchurch** [comment]
As of what is currently in master branch, I've tried several ways to reproduce this on Chrome v85.0.4183.102 macOS

- with `config.json` `options.allowreauth` set to either `true` or `false`
- using an invalid username / password

When `options.allowreauth` is set to `false`, works as designed and a failure will not re-prompt and you will need to close out the browser and try again.

![image](https://user-images.githubusercontent.com/1668075/93469768-ef456a80-f8be-11ea-94d5-fbf1c42d3f97.png)

<img width="688" alt="image" src="https://user-images.githubusercontent.com/1668075/93469813-fe2c1d00-f8be-11ea-9a11-0d627230170f.png">

When `options.allowreauth` is set to `true`, works as designed (I do get the `logBtn is not defined` error in the console HOWEVER I also receive `re-authenticating` console message, and the user is redirected to /ssh/reauth for re-authentication. When proper credentials are provided the user is then redirected back to their requested host and the session establishes correctly. 

Using invalid user name / password:
![image](https://user-images.githubusercontent.com/1668075/93469976-3cc1d780-f8bf-11ea-853d-5fe04bd620e8.png)

After redirect and correct username / password entered:
![image](https://user-images.githubusercontent.com/1668075/93470079-59f6a600-f8bf-11ea-865c-91646d066414.png)

Note, for me to witness the `logBtn is not defined` console message I had to use the 'Preserve log` option in Chrome to even see this. Under normal circumstances it redirects so fast that I'm unable to detect this.

I can work to eliminate this logBtn error, which should just take some refactoring of the client js, this should still work properly. Please verify wether or not the client is prompted for authentication.

**Comment by Jiehong** [comment]
I also get this in Firefox, with an infinite redirect rule (linked to the other bug where firefox does not update the basic auth credentials).

**Comment by billchurch** [comment]
There's not a way to fix this with Basic-Auth and Firefox that I can determine... If anyone has any ideas I'll open, but I think we'll need to switch to modal or some other way to collect credentials.
