### ISSUE TITLE
can we do a key based authentication for ssh with WebSSH2?

### ISSUE THREAD

**Issue by hiteshsethi** [billchurch/WebSSH2#19]
Currently webssh2 is asking username and password for the remote connection, how can we modify it to do a key based authentication in a secure way.

PS: I've seen ssh2 package takes private key as input.

**Comment by billchurch** [comment]
Wouldn't be too difficult to do this, give me a day or so and I can make a branch for this, at least for a proof of concept. 

How would you like to pass the key to the application? Keeping that key safe would be the trick, would you want the user to upload it every time they go to the application? Or store it persistently? Would the key be protected by a pass phrase or what?

**Comment by hiteshsethi** [comment]
Great thanks, I've seen the code properly now, we can modify the ssh2.client connect method args to use privateKey. Do you see it as a feature, we can have a dropdown on the first dialog box to choose auth mechanism(userpass or privatekey based). 

User can upload private key everytime, and it will deleted automatically after socket closes. 

I can make it and raise a PR if you want?

**Comment by billchurch** [comment]
@hiteshsethi 

Yes, I definitely see this as a feature. I'm struggling how to best implement it. First thought is a POST var (over TLS/SSL obviously). The thing I don't like about that is I feel that an SSH private key is more "valuable" than a password and I worry about MITM. Over TLS/SSL it should be less of a problem, but usually the environments I foresee this being used in would use self-signed certificates and have horrible TLS/SSL hygiene. There's also not a way to support a key locked in an HSM (like a smart card, YubiKey, etc...) since WebSSH2 will need the actual key.

Any thoughts here? I'm fine with implementing this with some caveats of course.

**Comment by billchurch** [comment]
Off topic and responded to #63 already.

**Comment by Rockermog** [comment]
Hi @billchurch / @hiteshsethi,

Could you pls let me know if there was osme work done wrt reading keys instead of pwd for authentication?
