### ISSUE TITLE
Some problems about displaying Chinese characters

### ISSUE THREAD

**Issue by Vinsmoke66** [billchurch/webssh2#208]
When I use webSSH2 on docker to see mysql data, it could not accurate show some Chinese characters like this:
![image](https://user-images.githubusercontent.com/21305459/92688911-bcf0b600-f370-11ea-9f70-3ec196dd1b10.png)

**Comment by Mikej81** [comment]
Chinese characters are not currently supported.

**Comment by billchurch** [comment]
No official support for non-latin characters outside of what xterm.js project provides. I recommend checking https://github.com/xtermjs/xterm.js/issues to see if your issue is reported and addressed, if so link back here and we can make accommodations to update xterm.js to the version which resolves this.
