### ISSUE TITLE
HTTPS Support

### ISSUE THREAD

**Issue by d3cr1pt** [billchurch/webssh2#220]
I need to run the webssh2 using https, and i can't find a way to it.

**Comment by plmartini** [comment]
Hi, you should schedule an enhancement in the app.js file.

Something like this:

var options = {
          key: fs.readFileSync('/tmp/privateKey.key'),
          cert: fs.readFileSync('/tmp/publicCert.crt')
        };

var servers = require('https').Server(options, app)

var ios = require('socket.io')(servers, { serveClient: false})

.
.
.
.
.

**Comment by vrej-ab** [comment]
Hi @d3cr1pt 
I have the same requirement, have you tried the suggested method by **plmartini**? Or find something better?

**Comment by billchurch** [comment]
Honestly the best way to do this is to put a proxy in front of it like [NGINX](https://www.nginx.com/blog/5-performance-tips-for-node-js-applications/).

Node can do this, but it's not great at it. Closing this for now, but feel free to comment more if you have config ideas on how to implement this. I wouldn't want to do it by default for the application (at least not yet) since there is a performance impact to the application doing extra encryption.

**Comment by billchurch** [comment]
see https://github.com/billchurch/webssh2-nginx for an example of setting up NGINX to proxy HTTPS for this solution

**Comment by vrej-ab** [comment]
Thx a lot)).
