### ISSUE TITLE
Multiple sessions in separete iframes issues

### ISSUE THREAD

**Issue by lpiskuno** [billchurch/webssh2#264]
Depending on the type of issue, please include the follwing information:
- Node and NPM Version
  - `node -v`
  - v14.17.6
  - `npm -v`
  - 6.14.15

- WebSSH2 release version
  - `grep version app/package.json`
  -   "version": "0.4.2",
    "release": "standard-version"
    "standard-version": "^9.3.0",

When using two iframes and trying to connect to ssh ip1 and ip2, both iframes end up with showing connection to only one server ip1
```
<!DOCTYPE html>
<html>
<body>

<iframe src="http://localhost:2222/ssh/host/ip1" width="100%">
</iframe>

<iframe src="http://localhost.93:2222/ssh/host/ip2" width="100%">
</iframe>

</body>
</html>
```

**Comment by billchurch** [comment]
I don't really know a good way to implement this for your use-case. This might be something best saved for a re-write of the auth system and sending creds and host information directly to the websocket.

I played around with this and it kind of works, but i hate it and wouldn't use it in production. But you could use Javascript to delay or stagger the loading. Still makes auth weird because if you're using the HTTP Basic Auth method you'll get prompts and won't know which server you're authenticating to.

Instead of using timing below, you could use something else more deterministic? Monitoring the DOM isn't really useful but might be a start.

```
<!DOCTYPE html>
<html>
<body>

<iframe id="frame1" src="http://localhost:2222/ssh/host/192.168.0.1" width="100%">
</iframe>

<iframe id="frame2" width="100%">
</iframe>

</body>
<script>
  window.setTimeout(function () {
      var iframe = document.getElementById('frame2');
      iframe.setAttribute('src', 'http://localhost:2222/ssh/host/192.168.0.20');
  }, 5000);    
</script>
</html>
```
