### ISSUE TITLE
Fill and send command from JS

### ISSUE THREAD

**Issue by mattpass** [billchurch/WebSSH2#30]
I figured out that can run ```term.write('php test.php');``` to inject text onto the command prompt but how can I then send it? term.send() doesn't appear to do what I need and appears to be something internal.

Is there an easy way to submit this (looked into keyboard events but that seems messy, nothing methods available and I'm unsure what's available in websockets in this repo in order to submit a command).

Any tips on how to trigger a command from browser hugely appreciated!

**Comment by billchurch** [comment]
Well, a bit out of scope for this application, but what you probably want to do is use the socket.emit property instead of the term properties.

https://github.com/billchurch/WebSSH2/blob/72acb0dcc409a4262451d0dc95e1fb421535ab13/src/js/client.js#L92

After session setup, somewhere... You can do something like this on the client.js:
socket.emit('data', "echo this is my thing to send to ssh terminal")

Remember that /src/client.js is the uncompiled js, once you modify that you'll need to do an "npm build" to put everything together in /client/...

**Comment by mattpass** [comment]
@billchurch Thanks Bill - that just about covers things. It needs to be followed up with this tho:
```
term.keyPress({"charCode" : 13});
```
...to actually trigger the command it seems.

So you're totally right:
```
term.write('ls');
term.keyPress({"charCode" : 13});
```
Does nothing, but your suggestion followed by simulating pressing Enter does work:
```
socket.emit('data', 'ls');
term.keyPress({"charCode" : 13});
```
