### ISSUE TITLE
Entering URL for WebSSH2 throws error canoot get to host

### ISSUE THREAD

**Issue by masavanu** [billchurch/WebSSH2#63]
Hi Everyone,

I am trying to setup WedSSH2 on my system.

I followed follwed instruction :- https://github.com/vertazzar/WebSSH2

Clone the repository--> git clone git://github.com/vertazzar/WebSSH2
npm install
npm start. The npm started successfully, but when I enter URL--http://10.11.100.97:2222/ssh/host/10.11.100.252
It throws me an error saying cannot get to host /ssh/host/10.11.100.252

Any idea?

**Comment by billchurch** [comment]
I don’t know who @vertazzar is, you probably want to open this on that repository. That fork of vertazzar’s is over a year behind. 

Mine is the original repository and actively maintained. Try pulling a release from here and see what you get, closing for now.

**Comment by vertazzar** [comment]
my fork just added ssl support and multiple connections 

I don't know what's the status of this repository on that. As for my fork, as memory serves, that error is because the server accepts POST method to create a gui, so first make a form

```


<!DOCTYPE html>
<html>
<head>
    <title></title>
</head>
<body>
    <form method="post" action="http://10.11.100.97:2222/ssh" target="shell">
        <p>
            <label>Username</label>
            <input type="text" name="username" />
        </p>
        <p>
            <label>Password</label>
            <input type="text" name="password">
        </p>
        <p>
            <label>Host</label>
            <input type="text" name="host">
        </p>
        <p>
            <input type="submit" value="submit" />
        </p>
    </form>
    <iframe style="width:1000px;height:700px;" name="shell"></iframe>
</body>
</html>

```

after you submit the credentials, it should show the GUI and start the SSH connection

as the code is over a year old, you might want to use this repository instead
